### ISSUE TITLE
Website scrolling issue with the Hack site

### ISSUE THREAD

**Issue by chrissimpkins** [source-foundry/source-foundry.github.io#1]
From Hack font issue report https://github.com/chrissimpkins/Hack/issues/31

> Please do not interfere with scrolling on this site: http://sourcefoundry.org/hack/

**Comment by Calinou** [comment]
It also seems to prevent zooming with Ctrl+Mouse wheel in Chromium.

**Comment by chrissimpkins** [comment]
@jublo any idea what might be causing this issue?

**Comment by jublo** [comment]
It is the smoothScroll plugin.

```html
    <!-- JS Implementing Plugins -->
    <script type="text/javascript" src="assets/plugins/smoothScroll.js"></script>
```

https://github.com/source-foundry/source-foundry.github.io/blob/37f4c8146f2ddf265523eeaaa65b0b65c1a39dd0/hack/assets/plugins/smoothScroll.js

**Comment by chrissimpkins** [comment]
good or bad thing?

**Comment by jublo** [comment]
@nwalke @burodepeper Please add your comments for/against smoothScroll.

**Comment by burodepeper** [comment]
@burodepeper Bad thing. I personally have no issues with the website, but hijackin/changing default behavior in an inteface is a big no-no. If the plugin is also used to move between sections, we need to find an alternative. Not able to look into that right now.

**Comment by nwalke** [comment]
On 27" 4k monitors, the speed is noticeably different.  If I scroll on this Github issue page, and then switch to that site, it's maddening as there's nothing I can do to turn it off. I guess I just don't understand what the point of it is.

**Comment by chrissimpkins** [comment]
@nwalke thanks for the input.  We will address this.
