### ISSUE TITLE
Hard to read copy

### ISSUE THREAD

**Issue by Rask** [source-foundry/source-foundry.github.io#2]
Some text passages are either in a small font-size or in a dim gray color. It is hard to read. Some examples.

-   "Features" (list items)
-   "Distinct Glyph Shapes" (paragraph copy)

I hit Ctrl-+ twice and those parts are still a bit difficult.

**Comment by chrissimpkins** [comment]
Thanks Rask.  I have had a few people discuss this with me outside of Github as well.  The general consensus is that I should increase the contrast to make this more legible   The other users were on Windows with Chrome.  What platform and browser are you using and do you think that this would address it?

**Comment by chrissimpkins** [comment]
Rask, I increased the contrast on the body copy without an adjustment in the size of the type.  Is this more legible?
